# -*- coding: utf-8 -*-
"""教材非官方 Digital 库 / 缺失 74xx 的考试外壳定义。

每条：DIP pinNumber + 教材常用脚名 + 方向（in/out，仅影响 .dig 里 In/Out 元件）。
出图用；多数无完整模拟行为（黑盒符号）。重建：build_chip_library.py
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

# pin: (label, pin_number, "in"|"out")
DeviceDef = dict[str, Any]

# Digital 库内 CMOS 命名怪异：744017 = 4017 等 → 教材名映射到官方 dig
DIGITAL_CMOS_ALIASES: dict[str, str] = {
    "4002": "744002",
    "CC4002": "744002",
    "CD4002": "744002",
    "4075": "744075",
    "CC4075": "744075",
    "CD4075": "744075",
    "4017": "744017",
    "CC4017": "744017",
    "CD4017": "744017",
    "40105": "7440105",
    "CC40105": "7440105",
    "CD40105": "7440105",
    "7266": "747266",
    "CC7266": "747266",
}

# 功能近似代用（出图可用，须在 IR notes 声明）
FUNCTIONAL_SUBSTITUTES: dict[str, str] = {
    "7492": "7490",  # 分频族近似；模制不同须人工确认
    "74290": "7490",
    "74293": "7493",
    "74393": "7493",
    "74192": "74193",  # 十进制 vs 二进制加减；脚位近似
    "74251": "74151",
    "74152": "74151",
}


def _pins(*items: tuple[str, int, str]) -> list[dict[str, Any]]:
    return [{"label": a, "num": b, "dir": c} for a, b, c in items]


CUSTOM_DEVICES: dict[str, DeviceDef] = {
    # —— 定时器 ——
    "NE555": {
        "family": "timer",
        "desc": "555 timer exam shell (8-DIP)",
        "width": 4,
        "pins": _pins(
            ("GND", 1, "in"),
            ("TRIG", 2, "in"),
            ("OUT", 3, "out"),
            ("RESET", 4, "in"),
            ("CTRL", 5, "in"),
            ("THRES", 6, "in"),
            ("DISCH", 7, "out"),
            ("VCC", 8, "in"),
        ),
        "aliases": ["555", "LMC555", "SE555", "ICM555"],
    },
    "NE556": {
        "family": "timer",
        "desc": "556 dual timer exam shell (14-DIP) — timer A pins",
        "width": 5,
        "pins": _pins(
            ("DISCH_A", 1, "out"),
            ("THRES_A", 2, "in"),
            ("CTRL_A", 3, "in"),
            ("RESET_A", 4, "in"),
            ("OUT_A", 5, "out"),
            ("TRIG_A", 6, "in"),
            ("GND", 7, "in"),
            ("TRIG_B", 8, "in"),
            ("OUT_B", 9, "out"),
            ("RESET_B", 10, "in"),
            ("CTRL_B", 11, "in"),
            ("THRES_B", 12, "in"),
            ("DISCH_B", 13, "out"),
            ("VCC", 14, "in"),
        ),
        "aliases": ["556"],
    },
    # —— CMOS 教材高频 ——
    "CC4069": {
        "family": "cmos",
        "desc": "hex inverter (like 7404)",
        "width": 5,
        "pins": _pins(
            ("1A", 1, "in"),
            ("1Y", 2, "out"),
            ("2A", 3, "in"),
            ("2Y", 4, "out"),
            ("3A", 5, "in"),
            ("3Y", 6, "out"),
            ("GND", 7, "in"),
            ("4Y", 8, "out"),
            ("4A", 9, "in"),
            ("5Y", 10, "out"),
            ("5A", 11, "in"),
            ("6Y", 12, "out"),
            ("6A", 13, "in"),
            ("VDD", 14, "in"),
        ),
        "aliases": ["4069", "CD4069"],
    },
    "CC40106": {
        "family": "cmos",
        "desc": "hex Schmitt inverter",
        "width": 5,
        "pins": _pins(
            ("1A", 1, "in"),
            ("1Y", 2, "out"),
            ("2A", 3, "in"),
            ("2Y", 4, "out"),
            ("3A", 5, "in"),
            ("3Y", 6, "out"),
            ("GND", 7, "in"),
            ("4Y", 8, "out"),
            ("4A", 9, "in"),
            ("5Y", 10, "out"),
            ("5A", 11, "in"),
            ("6Y", 12, "out"),
            ("6A", 13, "in"),
            ("VDD", 14, "in"),
        ),
        "aliases": ["40106", "CD40106"],
    },
    "CC4007": {
        "family": "cmos",
        "desc": "dual complementary pair + inverter (exam labels)",
        "width": 5,
        "pins": _pins(
            ("D_A", 1, "in"),
            ("G_A", 2, "in"),
            ("S_A", 3, "in"),
            ("S_B", 4, "in"),
            ("G_B", 5, "in"),
            ("D_B", 6, "in"),
            ("VSS", 7, "in"),
            ("D_C", 8, "out"),
            ("G_C", 9, "in"),
            ("S_C", 10, "in"),
            ("G_D", 11, "in"),
            ("S_D", 12, "in"),
            ("D_D", 13, "out"),
            ("VDD", 14, "in"),
        ),
        "aliases": ["4007", "CD4007"],
    },
    "CC4027": {
        "family": "cmos",
        "desc": "dual JK flip-flop",
        "width": 5,
        "pins": _pins(
            ("1J", 1, "in"),
            ("1Q", 2, "out"),
            ("1~Q", 3, "out"),
            ("1CLK", 4, "in"),
            ("1~R", 5, "in"),
            ("1K", 6, "in"),
            ("1~S", 7, "in"),
            ("VSS", 8, "in"),
            ("2~S", 9, "in"),
            ("2K", 10, "in"),
            ("2~R", 11, "in"),
            ("2CLK", 12, "in"),
            ("2~Q", 13, "out"),
            ("2Q", 14, "out"),
            ("2J", 15, "in"),
            ("VDD", 16, "in"),
        ),
        "aliases": ["4027", "CD4027"],
    },
    "CC4024": {
        "family": "cmos",
        "desc": "7-stage ripple binary counter",
        "width": 5,
        "pins": _pins(
            ("Q1", 1, "out"),
            ("Q2", 2, "out"),
            ("~MR", 3, "in"),
            ("Q7", 4, "out"),
            ("Q6", 5, "out"),
            ("Q5", 6, "out"),
            ("Q4", 7, "out"),
            ("VSS", 8, "in"),
            ("Q3", 9, "out"),
            ("NC", 10, "in"),
            ("NC2", 11, "in"),
            ("CLK", 12, "in"),
            ("NC3", 13, "in"),
            ("VDD", 14, "in"),
        ),
        "aliases": ["4024", "CD4024"],
    },
    "CC4510": {
        "family": "cmos",
        "desc": "BCD up/down counter",
        "width": 5,
        "pins": _pins(
            ("PE", 1, "in"),
            ("Q4", 2, "out"),
            ("P4", 3, "in"),
            ("P1", 4, "in"),
            ("~CI", 5, "in"),
            ("Q1", 6, "out"),
            ("~CO", 7, "out"),
            ("VSS", 8, "in"),
            ("U/~D", 9, "in"),
            ("Q2", 10, "out"),
            ("P2", 11, "in"),
            ("P3", 12, "in"),
            ("Q3", 13, "out"),
            ("CLK", 14, "in"),
            ("~MR", 15, "in"),
            ("VDD", 16, "in"),
        ),
        "aliases": ["4510", "CD4510"],
    },
    "CC40192": {
        "family": "cmos",
        "desc": "decade up/down counter (often paired with 74LS192)",
        "width": 5,
        "pins": _pins(
            ("B", 1, "in"),
            ("Q1", 2, "out"),
            ("Q0", 3, "out"),
            ("~DOWN", 4, "in"),
            ("~UP", 5, "in"),
            ("Q2", 6, "out"),
            ("Q3", 7, "out"),
            ("VSS", 8, "in"),
            ("D", 9, "in"),
            ("C", 10, "in"),
            ("~LOAD", 11, "in"),
            ("~CO", 12, "out"),
            ("~BO", 13, "out"),
            ("CLR", 14, "in"),
            ("A", 15, "in"),
            ("VDD", 16, "in"),
        ),
        "aliases": ["40192", "CD40192"],
    },
    # —— DAC / ADC ——
    "AD7520": {
        "family": "dac",
        "desc": "10-bit multiplying DAC (exam pin labels)",
        "width": 6,
        "pins": _pins(
            ("OUT1", 1, "out"),
            ("OUT2", 2, "out"),
            ("GND", 3, "in"),
            ("DB1", 4, "in"),
            ("DB2", 5, "in"),
            ("DB3", 6, "in"),
            ("DB4", 7, "in"),
            ("DB5", 8, "in"),
            ("DB6", 9, "in"),
            ("DB7", 10, "in"),
            ("DB8", 11, "in"),
            ("DB9", 12, "in"),
            ("DB10", 13, "in"),
            ("VREF", 14, "in"),
            ("RFB", 15, "out"),
            ("VDD", 16, "in"),
        ),
        "aliases": [],
    },
    "DAC0808": {
        "family": "dac",
        "desc": "8-bit current-output DAC exam shell",
        "width": 5,
        "pins": _pins(
            ("NC", 1, "in"),
            ("GND", 2, "in"),
            ("VREF-", 3, "in"),
            ("VREF+", 4, "in"),
            ("COMP", 5, "in"),
            ("IOUT", 6, "out"),
            ("VEE", 7, "in"),
            ("D7", 8, "in"),
            ("D6", 9, "in"),
            ("D5", 10, "in"),
            ("D4", 11, "in"),
            ("D3", 12, "in"),
            ("D2", 13, "in"),
            ("D1", 14, "in"),
            ("D0", 15, "in"),
            ("VCC", 16, "in"),
        ),
        "aliases": ["DAC0806", "DAC0807", "DAC0800", "DAC0830"],
    },
    "ADC0820": {
        "family": "adc",
        "desc": "8-bit ADC exam shell (simplified)",
        "width": 6,
        "pins": _pins(
            ("VIN", 1, "in"),
            ("DB0", 2, "out"),
            ("DB1", 3, "out"),
            ("DB2", 4, "out"),
            ("DB3", 5, "out"),
            ("WR", 6, "in"),
            ("MODE", 7, "in"),
            ("RD", 8, "in"),
            ("INT", 9, "out"),
            ("GND", 10, "in"),
            ("DB4", 11, "out"),
            ("DB5", 12, "out"),
            ("DB6", 13, "out"),
            ("DB7", 14, "out"),
            ("CS", 15, "in"),
            ("VCC", 16, "in"),
            ("VREF", 17, "in"),
            ("OFLOW", 18, "out"),
            ("NC", 19, "in"),
            ("VIN-", 20, "in"),
        ),
        "aliases": [],
    },
    # —— 运放（DAC 题外接）——
    "OPAMP": {
        "family": "analog",
        "desc": "ideal op-amp exam shell (not DIP; 5 pins layout as 8-DIP style)",
        "width": 4,
        "pins": _pins(
            ("OFFSET+", 1, "in"),
            ("IN-", 2, "in"),
            ("IN+", 3, "in"),
            ("V-", 4, "in"),
            ("OFFSET-", 5, "in"),
            ("OUT", 6, "out"),
            ("V+", 7, "in"),
            ("NC", 8, "in"),
        ),
        "aliases": ["OpAmp", "LM741", "OP07"],
    },
    # —— PLD ——
    "GAL16V8": {
        "family": "pld",
        "desc": "GAL16V8 pin shell for structure diagrams",
        "width": 6,
        "pins": _pins(
            ("I1", 1, "in"),
            ("I2", 2, "in"),
            ("I3", 3, "in"),
            ("I4", 4, "in"),
            ("I5", 5, "in"),
            ("I6", 6, "in"),
            ("I7", 7, "in"),
            ("I8", 8, "in"),
            ("I9", 9, "in"),
            ("I10", 10, "in"),
            ("I11", 11, "in"),
            ("GND", 12, "in"),
            ("I12", 13, "in"),
            ("IO1", 14, "out"),
            ("IO2", 15, "out"),
            ("IO3", 16, "out"),
            ("IO4", 17, "out"),
            ("IO5", 18, "out"),
            ("IO6", 19, "out"),
            ("VCC", 20, "in"),
        ),
        "aliases": [],
    },
    # —— 缺失 74xx MSI（官方 dig 无）——
    "74121": {
        "family": "74xx",
        "desc": "monostable multivibrator",
        "width": 5,
        "pins": _pins(
            ("~Q", 1, "out"),
            ("NC", 2, "in"),
            ("A1", 3, "in"),
            ("A2", 4, "in"),
            ("B", 5, "in"),
            ("~R", 6, "in"),
            ("GND", 7, "in"),
            ("Cext", 8, "in"),
            ("RCext", 9, "in"),
            ("Rint", 10, "in"),
            ("NC2", 11, "in"),
            ("NC3", 12, "in"),
            ("Q", 13, "out"),
            ("VCC", 14, "in"),
        ),
        "aliases": [],
    },
    "74122": {
        "family": "74xx",
        "desc": "retriggerable monostable",
        "width": 5,
        "pins": _pins(
            ("A1", 1, "in"),
            ("A2", 2, "in"),
            ("B1", 3, "in"),
            ("B2", 4, "in"),
            ("CLR", 5, "in"),
            ("~Q", 6, "out"),
            ("GND", 7, "in"),
            ("Cext", 8, "in"),
            ("RCext", 9, "in"),
            ("Rint", 10, "in"),
            ("Q", 11, "out"),
            ("NC", 12, "in"),
            ("NC2", 13, "in"),
            ("VCC", 14, "in"),
        ),
        "aliases": ["74LS122"],
    },
    "74123": {
        "family": "74xx",
        "desc": "dual retriggerable monostable",
        "width": 5,
        "pins": _pins(
            ("1A", 1, "in"),
            ("1B", 2, "in"),
            ("1~CLR", 3, "in"),
            ("1~Q", 4, "out"),
            ("2Q", 5, "out"),
            ("2Cext", 6, "in"),
            ("2RCext", 7, "in"),
            ("GND", 8, "in"),
            ("2A", 9, "in"),
            ("2B", 10, "in"),
            ("2~CLR", 11, "in"),
            ("2~Q", 12, "out"),
            ("1Q", 13, "out"),
            ("1Cext", 14, "in"),
            ("1RCext", 15, "in"),
            ("VCC", 16, "in"),
        ),
        "aliases": ["74LS123"],
    },
    "74221": {
        "family": "74xx",
        "desc": "dual monostable",
        "width": 5,
        "pins": _pins(
            ("1A", 1, "in"),
            ("1B", 2, "in"),
            ("1~CLR", 3, "in"),
            ("1~Q", 4, "out"),
            ("2Q", 5, "out"),
            ("2Cext", 6, "in"),
            ("2Rext", 7, "in"),
            ("GND", 8, "in"),
            ("2A", 9, "in"),
            ("2B", 10, "in"),
            ("2~CLR", 11, "in"),
            ("2~Q", 12, "out"),
            ("1Q", 13, "out"),
            ("1Cext", 14, "in"),
            ("1Rext", 15, "in"),
            ("VCC", 16, "in"),
        ),
        "aliases": [],
    },
    "74168": {
        "family": "74xx",
        "desc": "sync 4-bit up/down decade counter",
        "width": 5,
        "pins": _pins(
            ("U/~D", 1, "in"),
            ("CLK", 2, "in"),
            ("P0", 3, "in"),
            ("P1", 4, "in"),
            ("P2", 5, "in"),
            ("P3", 6, "in"),
            ("~ENP", 7, "in"),
            ("GND", 8, "in"),
            ("~ENT", 9, "in"),
            ("~PE", 10, "in"),
            ("Q3", 11, "out"),
            ("Q2", 12, "out"),
            ("Q1", 13, "out"),
            ("Q0", 14, "out"),
            ("~RCO", 15, "out"),
            ("VCC", 16, "in"),
        ),
        "aliases": [],
    },
    "74180": {
        "family": "74xx",
        "desc": "9-bit odd/even parity generator/checker",
        "width": 5,
        "pins": _pins(
            ("D0", 1, "in"),
            ("D1", 2, "in"),
            ("D2", 3, "in"),
            ("D3", 4, "in"),
            ("D4", 5, "in"),
            ("D5", 6, "in"),
            ("D6", 7, "in"),
            ("GND", 8, "in"),
            ("D7", 9, "in"),
            ("EVEN", 10, "in"),
            ("ODD", 11, "in"),
            ("SUM_EVEN", 12, "out"),
            ("SUM_ODD", 13, "out"),
            ("NC", 14, "in"),
            ("NC2", 15, "in"),
            ("VCC", 16, "in"),
        ),
        "aliases": [],
    },
    "74183": {
        "family": "74xx",
        "desc": "dual carry-save full adder",
        "width": 5,
        "pins": _pins(
            ("1C0", 1, "in"),
            ("1B", 2, "in"),
            ("1A", 3, "in"),
            ("1S", 4, "out"),
            ("1C2", 5, "out"),
            ("2C2", 6, "out"),
            ("2S", 7, "out"),
            ("GND", 8, "in"),
            ("2A", 9, "in"),
            ("2B", 10, "in"),
            ("2C0", 11, "in"),
            ("NC", 12, "in"),
            ("NC2", 13, "in"),
            ("VCC", 14, "in"),
        ),
        "aliases": ["74LS183"],
    },
    "74192": {
        "family": "74xx",
        "desc": "sync decade up/down counter (exam; Digital 无 dig)",
        "width": 5,
        "pins": _pins(
            ("B", 1, "in"),
            ("Q1", 2, "out"),
            ("Q0", 3, "out"),
            ("DOWN", 4, "in"),
            ("UP", 5, "in"),
            ("Q2", 6, "out"),
            ("Q3", 7, "out"),
            ("GND", 8, "in"),
            ("D", 9, "in"),
            ("C", 10, "in"),
            ("~LD", 11, "in"),
            ("~CO", 12, "out"),
            ("~BO", 13, "out"),
            ("CLR", 14, "in"),
            ("A", 15, "in"),
            ("VCC", 16, "in"),
        ),
        "aliases": ["74LS192", "74HC192"],
    },
    "7475": {
        "family": "74xx",
        "desc": "4-bit bistable latch",
        "width": 5,
        "pins": _pins(
            ("1D", 1, "in"),
            ("1Q", 2, "out"),
            ("1~Q", 3, "out"),
            ("2Q", 4, "out"),
            ("2~Q", 5, "out"),
            ("2D", 6, "in"),
            ("2E", 7, "in"),
            ("GND", 8, "in"),
            ("3E", 9, "in"),
            ("3D", 10, "in"),
            ("3~Q", 11, "out"),
            ("3Q", 12, "out"),
            ("4~Q", 13, "out"),
            ("4Q", 14, "out"),
            ("4D", 15, "in"),
            ("VCC", 16, "in"),
        ),
        "aliases": ["74LS75"],
    },
    "7492": {
        "family": "74xx",
        "desc": "divide-by-12 counter exam shell",
        "width": 5,
        "pins": _pins(
            ("NC", 1, "in"),
            ("NC2", 2, "in"),
            ("Q2", 3, "out"),
            ("Q1", 4, "out"),
            ("GND", 5, "in"),
            ("Q3", 6, "out"),
            ("Q0", 7, "out"),
            ("NC3", 8, "in"),
            ("NC4", 9, "in"),
            ("~R0", 10, "in"),
            ("~R1", 11, "in"),
            ("NC5", 12, "in"),
            ("NC6", 13, "in"),
            ("CLK_A", 14, "in"),
            ("VCC", 15, "in"),
            ("CLK_B", 16, "in"),
        ),
        "aliases": ["74HC92"],
    },
    "74290": {
        "family": "74xx",
        "desc": "decade counter (async) exam shell",
        "width": 5,
        "pins": _pins(
            ("~R0_1", 1, "in"),
            ("~R0_2", 2, "in"),
            ("NC", 3, "in"),
            ("NC2", 4, "in"),
            ("VCC", 5, "in"),
            ("~R9_1", 6, "in"),
            ("~R9_2", 7, "in"),
            ("Q2", 8, "out"),
            ("Q1", 9, "out"),
            ("GND", 10, "in"),
            ("Q3", 11, "out"),
            ("Q0", 12, "out"),
            ("NC3", 13, "in"),
            ("CLK_A", 14, "in"),
            ("CLK_B", 15, "in"),
            ("NC4", 16, "in"),
        ),
        "aliases": ["74LS290"],
    },
    "74293": {
        "family": "74xx",
        "desc": "4-bit binary counter exam shell",
        "width": 5,
        "pins": _pins(
            ("~R0_1", 1, "in"),
            ("~R0_2", 2, "in"),
            ("NC", 3, "in"),
            ("NC2", 4, "in"),
            ("VCC", 5, "in"),
            ("NC3", 6, "in"),
            ("NC4", 7, "in"),
            ("Q2", 8, "out"),
            ("Q1", 9, "out"),
            ("GND", 10, "in"),
            ("Q3", 11, "out"),
            ("Q0", 12, "out"),
            ("NC5", 13, "in"),
            ("CLK_A", 14, "in"),
            ("CLK_B", 15, "in"),
            ("NC6", 16, "in"),
        ),
        "aliases": ["74LS293"],
    },
    "74393": {
        "family": "74xx",
        "desc": "dual 4-bit binary counter",
        "width": 5,
        "pins": _pins(
            ("1CLK", 1, "in"),
            ("1CLR", 2, "in"),
            ("1Q0", 3, "out"),
            ("1Q1", 4, "out"),
            ("1Q2", 5, "out"),
            ("1Q3", 6, "out"),
            ("GND", 7, "in"),
            ("2Q3", 8, "out"),
            ("2Q2", 9, "out"),
            ("2Q1", 10, "out"),
            ("2Q0", 11, "out"),
            ("2CLR", 12, "in"),
            ("2CLK", 13, "in"),
            ("VCC", 14, "in"),
        ),
        "aliases": ["74LS393"],
    },
    # —— 存储器（教材出现）——
    "2114": {
        "family": "memory",
        "desc": "1K x 4 SRAM exam shell",
        "width": 6,
        "pins": _pins(
            ("A6", 1, "in"),
            ("A5", 2, "in"),
            ("A4", 3, "in"),
            ("A3", 4, "in"),
            ("A0", 5, "in"),
            ("A1", 6, "in"),
            ("A2", 7, "in"),
            ("CS", 8, "in"),
            ("GND", 9, "in"),
            ("D0", 10, "out"),
            ("D1", 11, "out"),
            ("D2", 12, "out"),
            ("D3", 13, "out"),
            ("WE", 14, "in"),
            ("A9", 15, "in"),
            ("A8", 16, "in"),
            ("A7", 17, "in"),
            ("VCC", 18, "in"),
        ),
        "aliases": [],
    },
}


def write_shell_dig(name: str, meta: DeviceDef, out_dir: Path) -> Path:
    """生成黑盒 DIL .dig（仅 In/Out + pinNumber，供考试出图）。"""
    width = int(meta.get("width") or 5)
    desc = str(meta.get("desc") or name)
    pins = meta["pins"]
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<circuit>",
        "  <version>1</version>",
        "  <attributes>",
        "    <entry>",
        "      <string>shapeType</string>",
        "      <shapeType>DIL</shapeType>",
        "    </entry>",
        "    <entry>",
        "      <string>Description</string>",
        f"      <string>{desc}</string>",
        "    </entry>",
        "    <entry>",
        "      <string>lockedMode</string>",
        "      <boolean>true</boolean>",
        "    </entry>",
        "    <entry>",
        "      <string>Width</string>",
        f"      <int>{width}</int>",
        "    </entry>",
        "  </attributes>",
        "  <visualElements>",
    ]
    y = 100
    for p in pins:
        el = "Out" if p["dir"] == "out" else "In"
        lab = p["label"]
        num = p["num"]
        lines += [
            "    <visualElement>",
            f"      <elementName>{el}</elementName>",
            "      <elementAttributes>",
            "        <entry>",
            "          <string>Label</string>",
            f"          <string>{lab}</string>",
            "        </entry>",
            "        <entry>",
            "          <string>pinNumber</string>",
            f"          <string>{num}</string>",
            "        </entry>",
            "      </elementAttributes>",
            f'      <pos x="300" y="{y}"/>',
            "    </visualElement>",
        ]
        y += 40
    lines += [
        "  </visualElements>",
        "  <wires/>",
        "  <measurementOrdering/>",
        "</circuit>",
        "",
    ]
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{name}.dig"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def emit_all_shells(out_dir: Path) -> list[str]:
    written = []
    for name, meta in CUSTOM_DEVICES.items():
        write_shell_dig(name, meta, out_dir)
        written.append(name)
    return written
